In [2]:
import pandas as pd
ball=pd.read_csv('/Users/nifal/Downloads/Ball_By_Ball_Match_Data.csv')
match=pd.read_csv('/Users/nifal/Downloads/Match_Info.csv')

In [3]:
ball.shape

(295732, 16)

In [4]:
match.shape

(1243, 14)

In [5]:
ball.columns.tolist()

['ID',
 'Innings',
 'Overs',
 'BallNumber',
 'Batter',
 'Bowler',
 'NonStriker',
 'ExtraType',
 'BatsmanRun',
 'ExtrasRun',
 'TotalRun',
 'IsWicketDelivery',
 'PlayerOut',
 'Kind',
 'FieldersInvolved',
 'BattingTeam']

In [6]:
match.columns.tolist()

['match_number',
 'team1',
 'team2',
 'match_date',
 'toss_winner',
 'toss_decision',
 'result',
 'eliminator',
 'winner',
 'player_of_match',
 'venue',
 'city',
 'team1_players',
 'team2_players']

In [7]:
ball.head()

,ID,Innings,Overs,BallNumber,Batter,Bowler,NonStriker,ExtraType,BatsmanRun,ExtrasRun,TotalRun,IsWicketDelivery,PlayerOut,Kind,FieldersInvolved,BattingTeam
0,501208,1,0,1,S Sohal,Z Khan,S Dhawan,NaN,0,0,0,0,NaN,NaN,NaN,Deccan Chargers
1,501208,1,0,2,S Sohal,Z Khan,S Dhawan,NaN,1,0,1,0,NaN,NaN,NaN,Deccan Chargers
2,501208,1,0,3,S Dhawan,Z Khan,S Sohal,NaN,1,0,1,0,NaN,NaN,NaN,Deccan Chargers
3,501208,1,0,4,S Sohal,Z Khan,S Dhawan,NaN,0,0,0,0,NaN,NaN,NaN,Deccan Chargers
4,501208,1,0,5,S Sohal,Z Khan,S Dhawan,wides,0,1,1,0,NaN,NaN,NaN,Deccan Chargers

In [8]:
match.head()

,match_number,team1,team2,match_date,toss_winner,toss_decision,result,eliminator,winner,player_of_match,venue,city,team1_players,team2_players
0,501208,Deccan Chargers,Royal Challengers Bangalore,2011-04-14,Royal Challengers Bangalore,field,Win,NaN,Deccan Chargers,DW Steyn,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,"S Sohal, S Dhawan, KC Sangakkara, B Chipli, JP...","MA Agarwal, TM Dilshan, Z Khan, V Kohli, AB de..."
1,1216505,Royal Challengers Bangalore,Delhi Capitals,2020-11-02,Delhi Capitals,field,Win,NaN,Delhi Capitals,A Nortje,Sheikh Zayed Stadium,Abu Dhabi,"JR Philippe, D Padikkal, V Kohli, AB de Villie...","PP Shaw, S Dhawan, AM Rahane, SS Iyer, RR Pant..."
2,1359481,Delhi Capitals,Gujarat Titans,2023-04-04,Gujarat Titans,field,Win,NaN,Gujarat Titans,B Sai Sudharsan,"Arun Jaitley Stadium, Delhi",Delhi,"KK Ahmed, DA Warner, PP Shaw, MR Marsh, SN Kha...","J Little, WP Saha, Shubman Gill, B Sai Sudhars..."
3,1178398,Kolkata Knight Riders,Chennai Super Kings,2019-04-09,Chennai Super Kings,field,Win,NaN,Chennai Super Kings,DL Chahar,MA Chidambaram Stadium,Chennai,"CA Lynn, SP Narine, RV Uthappa, N Rana, KD Kar...","SR Watson, F du Plessis, SK Raina, AT Rayudu, ..."
4,1529313,Delhi Capitals,Kolkata Knight Riders,2026-05-24,Kolkata Knight Riders,field,Win,NaN,Delhi Capitals,Kuldeep Yadav,"Eden Gardens, Kolkata",Kolkata,"Kuldeep Yadav, Abishek Porel, KL Rahul, SU Par...","SP Narine, AM Rahane, FH Allen, MK Pandey, C G..."

In [9]:
ball.isnull().sum()

ID                       0
Innings                  0
Overs                    0
BallNumber               0
Batter                   0
Bowler                   0
NonStriker               0
ExtraType           279505
BatsmanRun               0
ExtrasRun                0
TotalRun                 0
IsWicketDelivery         0
PlayerOut           281027
Kind                281027
FieldersInvolved    285011
BattingTeam              0
dtype: int64

In [10]:
match.isnull().sum()

match_number          0
team1                 0
team2                 0
match_date            0
toss_winner           0
toss_decision         0
result                0
eliminator         1227
winner               25
player_of_match       0
venue                 0
city                 51
team1_players         0
team2_players         0
dtype: int64

In [11]:
ball['Batter']

0             S Sohal
1             S Sohal
2            S Dhawan
3             S Sohal
4             S Sohal
             ...
295727    Abdul Samad
295728     M Markande
295729     M Markande
295730     M Markande
295731        B Kumar
Name: Batter, Length: 295732, dtype: object

In [12]:
ball['Batter'].str.contains('Samson')

0         False
1         False
2         False
3         False
4         False
          ...
295727    False
295728    False
295729    False
295730    False
295731    False
Name: Batter, Length: 295732, dtype: bool

In [13]:
ball[ball['Batter'].str.contains('Samson')]['Batter'].unique()

array(['SV Samson'], dtype=object)

In [14]:
samson=ball[ball['Batter']=='SV Samson']

In [15]:
samson.shape

(3770, 16)

In [16]:
samson[['Batter', 'Overs', 'BallNumber', 'BatsmanRun', 'IsWicketDelivery', 'Kind','Bowler']].head(20)

,Batter,Overs,BallNumber,BatsmanRun,IsWicketDelivery,Kind,Bowler
2546,SV Samson,0,1,0,0,NaN,Avesh Khan
2547,SV Samson,0,2,0,1,caught,Avesh Khan
5497,SV Samson,0,5,0,0,NaN,R Vinay Kumar
5498,SV Samson,0,6,0,0,NaN,R Vinay Kumar
5500,SV Samson,1,2,4,0,NaN,P Suyal
5501,SV Samson,1,3,0,0,NaN,P Suyal
5502,SV Samson,1,4,4,0,NaN,P Suyal
5503,SV Samson,1,5,0,0,NaN,P Suyal
5504,SV Samson,1,6,1,0,NaN,P Suyal
5506,SV Samson,2,1,0,0,NaN,R Vinay Kumar
5507,SV Samson,2,2,0,0,NaN,R Vinay Kumar
5508,SV Samson,2,3,1,0,NaN,R Vinay Kumar
5510,SV Samson,2,5,1,0,NaN,R Vinay Kumar
5512,SV Samson,3,1,1,0,NaN,P Suyal
5515,SV Samson,3,4,1,0,NaN,P Suyal
5518,SV Samson,4,1,0,0,NaN,R Vinay Kumar
5519,SV Samson,4,2,4,0,NaN,R Vinay Kumar
5520,SV Samson,4,3,0,1,caught,R Vinay Kumar
6754,SV Samson,8,2,1,0,NaN,R Ashwin
6756,SV Samson,8,4,1,0,NaN,R Ashwin

In [17]:
total_runs  = samson['BatsmanRun'].sum()
total_balls = len(samson)
times_out   = samson['IsWicketDelivery'].sum()

In [18]:
print(total_runs)
print (total_balls)
print(times_out)

5181
3770
163

In [19]:
strike_rate =((total_runs/total_balls)*100)

In [20]:
print('strike_rate :',round(strike_rate,2))

strike_rate : 137.43

In [21]:
average=(total_runs/times_out)

In [22]:
print('average;',round(average,2))

average; 31.79

In [23]:
fours=(samson['BatsmanRun']==4).sum()

In [24]:
six=(samson['BatsmanRun']==6).sum()

In [25]:
print(fours)
print(six)

432
243

In [26]:
boundry_runs=((fours*4)+(six*6))
print(boundry_runs)

3186

In [27]:
dot=(samson['BatsmanRun']==0).sum()

In [28]:
print(dot)

1366

In [29]:
dot_pct=round((dot / total_balls) * 100, 2)

In [30]:
print(dot_pct)

36.23

In [31]:

innings_list = []

for (match_id, inn), grp in samson.groupby(['ID','Innings']):
    runs      = grp['BatsmanRun'].sum()
    balls     = len(grp)
    dismissed = int(grp['IsWicketDelivery'].sum() > 0)
    innings_list.append({
        'match_id' : match_id,
        'innings'  : inn,
        'runs'     : runs,
        'balls'    : balls,
        'dismissed': dismissed
    })

innings_df = pd.DataFrame(innings_list)
print(innings_df.head(10))

   match_id  innings  runs  balls  dismissed
0    598014        2    27     23          0
1    598036        2    63     42          1
2    598043        1    40     36          1
3    598047        2    10      6          1
4    598052        2    47     33          0
5    598058        2     0      5          1
6    598063        2     4      4          1
7    598065        2     5      7          1
8    598071        2    10     21          1
9    598072        1     0      2          1

In [32]:
ducks    = (innings_df['runs'] == 0).sum()
fifties  = ((innings_df['runs'] >= 50) & (innings_df['runs'] < 100)).sum()
hundreds = (innings_df['runs'] >= 100).sum()
highest  = innings_df['runs'].max()

print("===== MILESTONE SCORES =====")
print("Ducks    :", ducks)
print("50s      :", fifties)
print("100s     :", hundreds)
print("Highest  :", highest)

===== MILESTONE SCORES =====
Ducks    : 11
50s      : 27
100s     : 5
Highest  : 119

In [33]:
merged= ball.merge(match,left_on='ID',right_on='match_number',how='left')
samson_full = merged[merged['Batter'] =='SV Samson'].copy()

In [34]:
print(samson_full.shape)

(3770, 30)

In [35]:
print(samson_full[['ID','match_date','BatsmanRun']].head())

           ID  match_date  BatsmanRun
2546  1082646  2017-05-14           0
2547  1082646  2017-05-14           0
5497   829721  2015-04-14           0
5498   829721  2015-04-14           0
5500   829721  2015-04-14           4

In [36]:
samson_full['season']=pd.to_datetime(samson_full['match_date']).dt.year
print(samson_full['season'].head())

2546    2017
2547    2017
5497    2015
5498    2015
5500    2015
Name: season, dtype: int32

In [37]:
season_stats = samson_full.groupby('season').agg(
    balls=('BatsmanRun','count'),
    runs=('BatsmanRun','sum'),
    dismissed =('IsWicketDelivery','sum')
).reset_index()
print(season_stats)

    season  balls  runs  dismissed
0     2013    179   206          8
1     2014    280   339         13
2     2015    166   204         10
3     2016    265   291         10
4     2017    275   386         14
5     2018    325   441         14
6     2019    238   342         10
7     2020    242   375         12
8     2021    372   484         12
9     2022    321   458         16
10    2023    240   362         12
11    2024    367   531         11
12    2025    205   285          9
13    2026    295   477         12

In [38]:
season_stats['strike_rate'] = (season_stats['runs']/season_stats['balls']*100).round(2)
season_stats['average']=(season_stats['runs']/season_stats['dismissed']).round(2)
print(season_stats)

    season  balls  runs  dismissed  strike_rate  average
0     2013    179   206          8       115.08    25.75
1     2014    280   339         13       121.07    26.08
2     2015    166   204         10       122.89    20.40
3     2016    265   291         10       109.81    29.10
4     2017    275   386         14       140.36    27.57
5     2018    325   441         14       135.69    31.50
6     2019    238   342         10       143.70    34.20
7     2020    242   375         12       154.96    31.25
8     2021    372   484         12       130.11    40.33
9     2022    321   458         16       142.68    28.62
10    2023    240   362         12       150.83    30.17
11    2024    367   531         11       144.69    48.27
12    2025    205   285          9       139.02    31.67
13    2026    295   477         12       161.69    39.75

In [39]:
samson_full['ball_seq'] = samson_full['Overs'] * 6 + samson_full['BallNumber']
ball['ball_seq'] = ball['Overs'] * 6 + ball['BallNumber']

first_ball = samson_full.groupby(['ID','Innings'])['ball_seq'].min().reset_index()
print(first_ball.head())

       ID  Innings  ball_seq
0  598014        2        78
1  598036        2        19
2  598043        1        28
3  598047        2       105
4  598052        2        59

In [40]:
def batting_position(match_id, innings, first_seq):
    before_samson = ball[
        (ball['ID'] == match_id) &
        (ball['Innings'] == innings) &
        (ball['ball_seq'] < first_seq)
    ]
    batters_before = before_samson['Batter'].nunique()
    return batters_before + 1

first_ball['position'] = first_ball.apply(
    lambda row: batting_position(row['ID'], row['Innings'], row['ball_seq']),
    axis=1
)

print(first_ball.head(10))

       ID  Innings  ball_seq  position
0  598014        2        78         6
1  598036        2        19         3
2  598043        1        28         4
3  598047        2       105         6
4  598052        2        59         4
5  598058        2        23         4
6  598063        2        25         4
7  598065        2        53         4
8  598071        2        51         6
9  598072        1        57         4

In [41]:
first_ball = first_ball.merge(
    samson_full[['ID','Innings','season']].drop_duplicates(),
    on=['ID','Innings'],
    how='left'
)
print(first_ball.head(10))

       ID  Innings  ball_seq  position  season
0  598014        2        78         6    2013
1  598036        2        19         3    2013
2  598043        1        28         4    2013
3  598047        2       105         6    2013
4  598052        2        59         4    2013
5  598058        2        23         4    2013
6  598063        2        25         4    2013
7  598065        2        53         4    2013
8  598071        2        51         6    2013
9  598072        1        57         4    2013

In [42]:
position_by_season = first_ball.groupby('season')['position'].agg(
    lambda x: x.value_counts().idxmax()
).reset_index()

position_by_season.columns = ['season', 'most_common_position']
print(position_by_season)

    season  most_common_position
0     2013                     4
1     2014                     3
2     2015                     2
3     2016                     3
4     2017                     1
5     2018                     3
6     2019                     3
7     2020                     3
8     2021                     3
9     2022                     3
10    2023                     3
11    2024                     3
12    2025                     2
13    2026                     1

In [43]:
print(samson['Overs'].head(10))

2546    0
2547    0
5497    0
5498    0
5500    1
5501    1
5502    1
5503    1
5504    1
5506    2
Name: Overs, dtype: int64

In [44]:
def get_phase(over):
    if over < 6:
        return 'Powerplay'
    elif over <15:
        return 'Middle'
    else:
        return'Death'

In [45]:
samson=samson.copy()

In [46]:
samson['phase'] = samson['Overs'].apply(get_phase)

In [47]:
print (samson['phase'].value_counts())

phase
Middle       1998
Powerplay    1305
Death         467
Name: count, dtype: int64

In [48]:
phase_stats = samson.groupby('phase').agg(
    balls = ('BatsmanRun', 'count'),
    runs  = ('BatsmanRun', 'sum'),
    fours = ('BatsmanRun', lambda x: (x==4).sum()),
    sixes = ('BatsmanRun', lambda x: (x==6).sum()),
    dots  = ('BatsmanRun', lambda x: (x==0).sum())
).reset_index()

In [49]:
print (phase_stats)

       phase  balls  runs  fours  sixes  dots
0      Death    467   852     64     57   133
1     Middle   1998  2710    162    133   595
2  Powerplay   1305  1619    206     53   638

In [50]:
phase_stats['strike_rate']=(phase_stats['runs']/phase_stats['balls']*100).round(2)

In [51]:
print(phase_stats)

       phase  balls  runs  fours  sixes  dots  strike_rate
0      Death    467   852     64     57   133       182.44
1     Middle   1998  2710    162    133   595       135.64
2  Powerplay   1305  1619    206     53   638       124.06

In [52]:
matchup = samson.groupby('Bowler').agg(
    balls   = ('BatsmanRun', 'count'),
    runs    = ('BatsmanRun', 'sum'),
    fours   = ('BatsmanRun', lambda x: (x==4).sum()),
    sixes   = ('BatsmanRun', lambda x: (x==6).sum()),
    dots    = ('BatsmanRun', lambda x: (x==0).sum()),
    wickets = ('IsWicketDelivery', 'sum')
).reset_index()

print(matchup.sort_values('balls', ascending=False).head(10))

          Bowler  balls  runs  fours  sixes  dots  wickets
183  Rashid Khan    109   121      5      5    35        2
29       B Kumar     99   120     13      3    45        4
198    SP Narine     89    70      3      1    39        3
11      AR Patel     85   103      7      3    24        3
83     JJ Bumrah     82    89     12      1    38        3
216     UT Yadav     71   119     11      8    29        3
98     KH Pandya     70    95      9      0    10        1
210  T Natarajan     66   106     12      5    29        2
188       S Kaul     65   114      8      7    19        2
175    RA Jadeja     64    82      2      6    24        3

In [53]:
matchup['strike_rate']=(matchup['runs']/matchup['balls']*100).round(2)

In [54]:
print(matchup.sort_values('balls', ascending=False).head(10))

          Bowler  balls  runs  fours  sixes  dots  wickets  strike_rate
183  Rashid Khan    109   121      5      5    35        2       111.01
29       B Kumar     99   120     13      3    45        4       121.21
198    SP Narine     89    70      3      1    39        3        78.65
11      AR Patel     85   103      7      3    24        3       121.18
83     JJ Bumrah     82    89     12      1    38        3       108.54
216     UT Yadav     71   119     11      8    29        3       167.61
98     KH Pandya     70    95      9      0    10        1       135.71
210  T Natarajan     66   106     12      5    29        2       160.61
188       S Kaul     65   114      8      7    19        2       175.38
175    RA Jadeja     64    82      2      6    24        3       128.12

In [55]:
got_him = matchup[matchup['wickets'] > 0].sort_values('wickets', ascending=False)
print(got_him[['Bowler','balls','runs','wickets','strike_rate']].head(10))

             Bowler  balls  runs  wickets  strike_rate
226       YS Chahal     53    61        5       115.09
205     Shivam Mavi     27    34        5       125.93
29          B Kumar     99   120        4       121.21
124  MJ McClenaghan     17    22        4       129.41
135  Mohammed Siraj     42    41        4        97.62
48        DL Chahar     29    39        3       134.48
85        JO Holder     38    40        3       105.26
83        JJ Bumrah     82    89        3       108.54
62         HV Patel     26    27        3       103.85
161    PWH de Silva     32    38        3       118.75

In [56]:
highest_str= matchup[matchup['strike_rate'] > 0].sort_values('strike_rate', ascending=False)

In [57]:
print(highest_str[['Bowler','balls','runs','wickets','strike_rate']].head(10))

                      Bowler  balls  runs  wickets  strike_rate
61                HR Shokeen      5    15        0       300.00
131                  MS Gony      4    11        0       275.00
89   JPR Scantlebury-Searles      4    11        0       275.00
78             JA Richardson     11    30        0       272.73
159                 PP Hinge      7    19        0       271.43
184             Rasikh Salam      7    19        0       271.43
192                 SK Raina      3     8        0       266.67
74                 J Overton      3     8        0       266.67
101               KT Maphaka      3     8        0       266.67
117                 M Morkel      6    16        0       266.67

In [58]:
print(samson[samson['IsWicketDelivery'] == 1]['Kind'].value_counts())

Kind
caught               113
bowled                22
lbw                    8
run out                7
stumped                6
caught and bowled      5
retired out            1
retired hurt           1
Name: count, dtype: int64

In [59]:
samson.to_csv('samson_analysis.tick', index=False)
season_stats.to_csv('samson_season_stats.csv', index=False)
matchup.to_csv('samson_matchup.csv', index=False)
phase_stats.to_csv('samson_phase_stats.csv', index=False)

print('All files exported!')

All files exported!

In [60]:
import os
print(os.getcwd())

/Users/nifal

In [61]:
# ===== MILESTONES - 50s, 100s, Highest, Ducks per season =====
season_50s = []

for season, grp in samson_full.groupby('season'):
    innings_list = []
    for (match_id, inn), inn_grp in grp.groupby(['ID','Innings']):
        runs = inn_grp['BatsmanRun'].sum()
        innings_list.append(runs)
    
    innings_runs = pd.Series(innings_list)
    season_50s.append({
        'season'  : season,
        'fifties' : ((innings_runs >= 50) & (innings_runs < 100)).sum(),
        'hundreds': (innings_runs >= 100).sum(),
        'highest' : innings_runs.max(),
        'ducks'   : (innings_runs == 0).sum()
    })

milestones_df = pd.DataFrame(season_50s)
print('===== MILESTONES PER SEASON =====')
print(milestones_df)
milestones_df.to_csv('samson_milestones.csv', index=False)

# ===== OVERALL MILESTONES =====
all_innings = []
for (match_id, inn), inn_grp in samson_full.groupby(['ID','Innings']):
    runs = inn_grp['BatsmanRun'].sum()
    all_innings.append(runs)

all_innings_runs = pd.Series(all_innings)
print()
print('===== OVERALL CAREER MILESTONES =====')
print('Fifties  :', ((all_innings_runs >= 50) & (all_innings_runs < 100)).sum())
print('Hundreds :', (all_innings_runs >= 100).sum())
print('Highest  :', all_innings_runs.max())
print('Ducks    :', (all_innings_runs == 0).sum())

# ===== WICKETKEEPING - Catches and Stumpings =====
samson_fielding = ball[ball['FieldersInvolved'].str.contains('Samson', na=False)].copy()

fielding_stats = samson_fielding['Kind'].value_counts().reset_index()
fielding_stats.columns = ['dismissal_type', 'count']

print()
print('===== WICKETKEEPING STATS =====')
print(fielding_stats)

fielding_stats.to_csv('samson_fielding.csv', index=False)

print()
print('All files exported!')

===== MILESTONES PER SEASON =====
    season  fifties  hundreds  highest  ducks
0     2013        1         0       63      2
1     2014        2         0       74      0
2     2015        1         0       76      0
3     2016        1         0       60      0
4     2017        2         1      102      2
5     2018        3         0       92      1
6     2019        0         1      102      0
7     2020        3         0       85      2
8     2021        2         1      119      0
9     2022        2         0       55      0
10    2023        3         0       66      2
11    2024        5         0       86      1
12    2025        1         0       66      0
13    2026        1         2      115      1

===== OVERALL CAREER MILESTONES =====
Fifties  : 27
Hundreds : 5
Highest  : 119
Ducks    : 11

===== WICKETKEEPING STATS =====
  dismissal_type  count
0         caught     90
1        run out     28
2        stumped     19

All files exported!